package io.github.scala_tessella.minimal_uniformity_three

import io.github.scala_tessella.research_core.*

import io.github.scala_tessella.research_core.DelaneySymbols.{DSet, DSymbol}
import scala.jdk.CollectionConverters.*
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

/** THE LOWER-BOUND LEMMAS, machine-checked — the hand cross-check of the paper's window bounds. Several
  * species fall to counting (tile stabilisers, corner orbits, chamber bounds) rather than to a bigger
  * exhaustion, and the arithmetic those arguments rest on is small enough to be re-derived on every run, so
  * it is pinned here and confronted with every banked witness rather than trusted to a hand computation.
  *
  * WHAT THE PAPER USES from this spec:
  *
  *   - the TILE-STABILISER reduction: corner-orbit counts of a regular n-gon under every stabiliser the
  *     crystallographic restriction allows, and the case tables they force per species. Its predictions are
  *     confronted with every banked witness and must be the observed counts — 7 for the 42-gon of the
  *     ten-orbit (3.7.42) pattern, 5 for the 20-gon of the seven-orbit (4.5.20) one, 3 for the 15-gon of the
  *     five-orbit (3.10.15) one;
  *   - the vertex-angle DIOPHANTINE tables: the completion alphabet at a corner of the largest tile,
  *     cross-checked against [[UClass.cyclicSubset]] so the enumeration cannot drift from the predicate the
  *     searches actually scan with;
  *   - the chamber bounds per species and orbit count, which is what makes a search window finite — the
  *     (3.10.15) chain (k ≤ 4 forces p6m and then C ≤ 24 chambers, making the 31–48 four-orbit window vacuous
  *     for that species) among them.
  *
  * WHAT IS RETAINED AS A CROSS-CHECK, its paper result having been superseded. The paper's distinct-letter
  * window theorem now closes (3.7.42) and (4.5.20) by a single argument, and the two routes below, which
  * closed them by hand before that theorem existed, were dropped from the manuscript. They are kept here
  * because they reach the same bounds by different means, in milliseconds, and a second route that agrees is
  * worth more than the lines it costs — but nothing in the paper rests on them:
  *
  *   - the ODD-SLICE theorem: the per-orbit vertex caps force C even above 12k − 6, checked against every
  *     D-set count the k = 3 searches have measured. Other tests here still reason from it (the thin C = 29
  *     slice, for one), so it is load-bearing inside this spec even though the manuscript dropped it;
  *   - the STABILISER CHAIN closing (3.7.42) at k ≤ 5 and (4.5.20) at k ≥ 6 — the V = 36 refutation, the
  *     20-gon collar analysis and the 45° rhombus. Superseded by the window theorem, which reaches further
  *     with less case analysis.
  *
  * All of it is integer arithmetic on small sets — the whole suite runs in milliseconds and stays in the
  * default (unguarded) tier.
  */
class UClassLowerBoundSpec extends AnyFlatSpec with Matchers:

  /** Rotation orders a finite subgroup of a wallpaper group may have (crystallographic restriction). */
  private val crystallographic = List(1, 2, 3, 4, 6)

  /** Rotation orders available to the stabiliser of a regular `n`-gon: divide `n` AND crystallographic. */
  private def admissibleRotations(n: Int): List[Int] = crystallographic.filter(n % _ == 0)

  /** Orbits of the corners `0 until n` of a regular n-gon under the stabiliser: the cyclic group generated by
    * the rotation through `n / m` steps, optionally extended by the reflection `i => c - i` (the two
    * reflection classes of a dihedral stabiliser are the two parities of `c`).
    */
  private def cornerOrbits(n: Int, m: Int, reflection: Option[Int]): Int =
    val step  = n / m
    val group = (0 until m).map(s => (i: Int) => Math.floorMod(i + s * step, n)) ++
      reflection.toList.flatMap(c => (0 until m).map(s => (i: Int) => Math.floorMod(c - i + s * step, n)))
    val seen  = scala.collection.mutable.Set.empty[Int]
    var count = 0
    for p <- 0 until n if !seen(p) do
      count += 1
      var orbit = Set(p)
      var grown = true
      while grown do
        val next = orbit.flatMap(q => group.map(_(q)))
        grown = next != orbit
        orbit = next
      seen ++= orbit
    count

  /** The least `k` forced by a tile of `n` corners whose stabiliser has rotation order `m`: over both
    * reflection classes and the rotation-only case, the SMALLEST orbit count — the best the adversary can do.
    */
  private def forcedK(n: Int, m: Int): Int =
    (cornerOrbits(n, m, None) +: (0 until n).map(c => cornerOrbits(n, m, Some(c)))).min

  it should "count corner orbits of a regular n-gon under each admissible stabiliser" in:
    // rotation-only stabilisers leave n/m orbits; a reflection can at best halve them
    cornerOrbits(15, 3, None) shouldBe 5
    cornerOrbits(15, 1, None) shouldBe 15
    cornerOrbits(10, 2, None) shouldBe 5
    // dihedral: 15 is odd so every mirror fixes exactly one corner; a decagon has both mirror classes
    (0 until 15).map(c => cornerOrbits(15, 3, Some(c))).distinct shouldBe Vector(3)
    (0 until 15).map(c => cornerOrbits(15, 1, Some(c))).distinct shouldBe Vector(8)
    (0 until 10).map(c => cornerOrbits(10, 2, Some(c))).distinct.sorted shouldBe Vector(3)
    (0 until 10).map(c => cornerOrbits(10, 1, Some(c))).distinct.sorted shouldBe Vector(5, 6)

  it should "force k >= 4 for (3.7.42) from the heptagon alone, with no case split" in:
    // 7 is coprime to every crystallographic rotation order, so a regular heptagon's stabiliser is at most a
    // single reflection: 7 corners, one fixed, three swapped pairs
    admissibleRotations(7) shouldBe List(1)
    forcedK(7, 1) shouldBe 4
    // the same degeneracy pins the regular pentagon of (4.5.20)
    admissibleRotations(5) shouldBe List(1)
    forcedK(5, 1) shouldBe 3

  it should "tabulate the stabiliser case split per open species" in:
    val cases = Map(
      42 -> Map(6 -> 4, 3 -> 7, 2 -> 11, 1 -> 21),
      20 -> Map(4 -> 3, 2 -> 5, 1 -> 10),
      15 -> Map(3 -> 3, 1 -> 8),
      10 -> Map(2 -> 3, 1 -> 5),
      12 -> Map(6 -> 1, 4 -> 2, 3 -> 2, 2 -> 3, 1 -> 6)
    )
    for (n, expected) <- cases do
      admissibleRotations(n).toSet shouldBe expected.keySet
      for (m, k) <- expected do withClue(s"$n-gon, rotation order $m: ")(forcedK(n, m) shouldBe k)

  it should "leave exactly one stabiliser pair alive for (3.10.15) at k <= 4" in:
    // every stabiliser type except D3 on the 15-gon and D2 on the decagon already forces k >= 5
    val survivors15 = admissibleRotations(15).filter(forcedK(15, _) <= 4)
    val survivors10 = admissibleRotations(10).filter(forcedK(10, _) <= 4)
    survivors15 shouldBe List(3)
    survivors10 shouldBe List(2)
    // and the survivors are DIHEDRAL: the rotation-only groups are already excluded
    cornerOrbits(15, 3, None) should be > 4
    cornerOrbits(10, 2, None) should be > 4

  // ---- L3: the vertex-angle Diophantine tables --------------------------------------------------------

  /** The least unit making every regular corner of `z` an integer number of π/N. */
  private def angleUnit(z: List[Int]): Int =
    def gcd(a: Int, b: Int): Int = if b == 0 then a else gcd(b, a % b)
    def lcm(a: Int, b: Int): Int = a / gcd(a, b) * b
    z.distinct.map(p => p / gcd(p, 2)).foldLeft(1)(lcm)

  /** Contiguous cyclic subwords of `z` up to rotation and reflection — the RVS candidates of condition (3).
    */
  private def rvsCandidates(z: List[Int]): List[List[Int]] = (1 to z.length)
    .flatMap(len => z.indices.map(r => (0 until len).map(i => z((r + i) % z.length)).toList))
    .groupBy(w => if w.reverse.mkString < w.mkString then w.reverse else w)
    .values
    .map(_.head)
    .toList
    .sortBy(w => (w.length, w.mkString))

  it should "derive the vertex-angle unit and the all-regular vertex per species" in:
    val units = Map(List(3, 7, 42) -> 21, List(3, 10, 15) -> 15, List(4, 5, 20) -> 10, List(3, 3, 4, 12) -> 6)
    for (z, n) <- units do
      angleUnit(z) shouldBe n
      def corner(p: Int) = n * (p - 2) / p
      // the full word is exactly a full turn, and NOTHING shorter is
      z.map(corner).sum shouldBe 2 * n
      for w <- rvsCandidates(z) if w.length < z.length do w.map(corner).sum should be < 2 * n

  it should "leave a four-letter alphabet at a corner of the largest tile" in:
    val expected = Map(
      List(3, 7, 42)  -> List(0, 7, 15, 22),
      List(3, 10, 15) -> List(0, 5, 12, 17),
      List(4, 5, 20)  -> List(0, 5, 6, 11)
    )
    for (z, residues) <- expected do
      val n      = angleUnit(z)
      val big    = z.max
      val atBig  = rvsCandidates(z).filter(_.contains(big))
      val actual = atBig.map(w => 2 * n - w.map(p => n * (p - 2) / p).sum).distinct.sorted
      withClue(s"z=$z: ")(actual shouldBe residues)
      // every enumerated RVS really is admissible under the production predicate
      for w <- atBig do withClue(s"$w in $z: ")(UClass.cyclicSubset(w, z) shouldBe true)
      // residue zero happens only at the full word: an all-regular vertex IS the z-vertex
      atBig.filter(w => w.map(p => n * (p - 2) / p).sum == 2 * n).foreach(_.length shouldBe z.length)

  // ---- the odd-slice theorem ----------------------------------------------------------------------

  /** The per-orbit vertex caps of `DelaneySymbols.vertexOrbitCap12`, valence >= 3: chains 4/6/12 by length
    * 1/2/>=3, cycles 8/12/24 by length 2/4/>=6.
    */
  private val vertexCaps    = List(4, 6, 12, 8, 12, 24)
  private val maxCap        = vertexCaps.max
  private val secondBestCap = vertexCaps.filter(_ < maxCap).max

  it should "force C even above 12k - 6, for every k (the odd-slice theorem)" in:
    maxCap shouldBe 24
    secondBestCap shouldBe 12
    // euclidean feasibility needs sum12 >= 2C; the largest sum strictly below 24k is 24k - 12, so once
    // 2C exceeds that, every orbit sits at cap 24 — attained only by a CYCLE, whose length is even
    for k <- 1 to 8 do
      val threshold = 12 * k - 6
      (24 * k - (maxCap - secondBestCap)) shouldBe 24 * k - 12
      (2 * threshold) shouldBe 24 * k - 12
    // the three odd slices at the top of each k-window are therefore empty
    def emptyOdd(k: Int) = ((12 * k - 6) + 1 to 12 * k).filter(_ % 2 == 1).toList
    emptyOdd(3) shouldBe List(31, 33, 35)
    emptyOdd(4) shouldBe List(43, 45, 47)
    emptyOdd(5) shouldBe List(55, 57, 59)

  it should "agree with every measured k = 3 D-set count" in:
    // staircase-universe counts banked by the obligation manifest and the band walks of 2026-08-29
    val measured = Map(
      8  -> 105,
      9  -> 76,
      10 -> 201,
      11 -> 165,
      12 -> 435,
      13 -> 367,
      14 -> 727,
      15 -> 534,
      16 -> 1213,
      17 -> 691,
      18 -> 1576,
      19 -> 687,
      21 -> 402,
      23 -> 220,
      25 -> 121,
      26 -> 2465,
      27 -> 25,
      28 -> 2014,
      29 -> 10,
      30 -> 1626,
      31 -> 0,
      32 -> 998,
      33 -> 0,
      34 -> 338,
      36 -> 293
    )
    for (c, n) <- measured do
      if c > 12 * 3 - 6 && c % 2 == 1 then withClue(s"C=$c is above the threshold and odd: ")(n shouldBe 0)
      else withClue(s"C=$c is below the threshold or even: ")(n should be > 0)

  // ---- the (3.10.15) chain ----------------------------------------------------------------------------

  it should "bound the (3.10.15) four-orbit symbol at 24 chambers, making the 31-48 window vacuous" in:
    val pointGroup                = 12 // p6m, forced by D3 on the 15-gon and D2 on the decagon
    // the 15-gon's three corner orbits have stabiliser orders 2, 1, 1 inside Stab = D3
    val vFrom15                   = List(2, 1, 1).map(pointGroup / _).sum
    vFrom15 shouldBe 30
    vFrom15 shouldBe 2 * 15 // and that is exactly the fifteen-gon corners per primitive cell
    // k <= 4 leaves at most one further vertex orbit, contributing at most 12
    val vMax                      = vFrom15 + pointGroup
    vMax shouldBe 42
    // faces per cell: 15-gons 12/6, decagons 12/4, the six-fold tile 12/12; it is not a regular hexagon,
    // since 6 is not a letter of z, so it carries at least 12 corners
    (pointGroup / 6, pointGroup / 4, pointGroup / 12) shouldBe (2, 3, 1)
    val knownCorners              = 2 * 15 + 3 * 10 + 12
    knownCorners shouldBe 72
    // 2E = sum n_f >= knownCorners + 3(F - 6) and E = V + F, so F <= 2V - 54 and C = 4E/12 = E/3
    def chamberBound(v: Int): Int =
      val f = 2 * v - (knownCorners - 3 * 6)
      val e = v + f
      4 * e / pointGroup
    chamberBound(vMax) shouldBe 24
    chamberBound(vFrom15) shouldBe 12
    // the G0 bound alone would have allowed 12k = 48: the window 31-48 cannot contain a four-orbit symbol
    chamberBound(vMax) should be < 12 * 4

  // ---- the generalised stabiliser chain, applied to the remaining open rows ------------------------------------

  /** The stabiliser counting chain in general. `anchor` is a regular n-gon whose letter occurs ONCE in z (so
    * no vertex meets two copies and corner orbits are read off the stabiliser); `pointGroup` is |G/T|;
    * `anchorStab` the order of Stab(anchor) and `anchorOrbits` its number of corner orbits; `k` the assumed
    * uniformity bound; `knownCorners` / `knownFaces` the corners and count of the face orbits forced to
    * exist. Returns (V low, V high, chamber bound).
    *
    * V is bounded below by the anchor's corners per cell (n · P/s, all distinct) and above by adding the at
    * most k − anchorOrbits remaining orbits at P each. Then 2E = Σ n_f ≥ knownCorners + 3(F − knownFaces)
    * with E = V + F (Euler on the torus) gives F ≤ 2V − (knownCorners − 3·knownFaces), and a symmetry fixing
    * a flag is the identity, so C = 4E/P.
    */
  private def chain(
      pointGroup: Int,
      n: Int,
      anchorStab: Int,
      anchorOrbits: Int,
      k: Int,
      knownCorners: Int,
      knownFaces: Int
  ): (Int, Int, Int) =
    val vLo = n * (pointGroup / anchorStab)
    val vHi = vLo + (k - anchorOrbits) * pointGroup
    val f   = 2 * vHi - (knownCorners - 3 * knownFaces)
    (vLo, vHi, 4 * (vHi + f) / pointGroup)

  it should "reproduce the (3.10.15) chain through the general formula" in:
    chain(
      pointGroup = 12,
      n = 15,
      anchorStab = 6,
      anchorOrbits = 3,
      k = 4,
      knownCorners = 2 * 15 + 3 * 10 + 12,
      knownFaces = 6
    ) shouldBe (30, 42, 24)

  it should "bound (3.7.42) at 21 chambers for k <= 4, inside the searched window" in:
    // under k <= 4 the 42-gon's only surviving stabiliser is D6: D3 and C6 leave 7 orbits, C3 14, C2/D1 21
    val survivors     =
      for
        m   <- admissibleRotations(42)
        dih <- List(false, true)
        q    = if dih then (0 until 42).map(c => cornerOrbits(42, m, Some(c))).min else cornerOrbits(42, m, None)
        if q <= 4
      yield (m, dih, q)
    survivors shouldBe List((6, true, 4))
    // D6 forces point group D6, so p6m. The anchor's 4 corner orbits EXHAUST k = 4: every vertex is a
    // corner of the single 42-gon per cell, and no further vertex orbit exists.
    // Forced faces: the 42-gon (1/cell, 42 corners); heptagons, whose stabiliser is at most a reflection
    // (7 is coprime to every crystallographic order) so at least 12/2 = 6 per cell, 42 corners; triangles,
    // at least 12/6 = 2 per cell, 6 corners.
    val (vLo, vHi, c) = chain(12, 42, 12, 4, 4, 42 + 6 * 7 + 2 * 3, 1 + 6 + 2)
    vLo shouldBe 42
    vHi shouldBe 42   // q = k, so no slack at all
    c shouldBe 21
    c should be <= 24 // inside the exhausted four-orbit window, which holds ZERO (3.7.42) candidates
    c should be < 12 * 4 // and far inside the G0 bound

  it should "bound (4.5.20) at 29 chambers for k <= 4, just outside the searched window" in:
    // under k <= 4 only D4 survives on the 20-gon: C4 and D2 leave 5 orbits, C2/D1 10, C1 20
    val survivors     =
      for
        m   <- admissibleRotations(20)
        dih <- List(false, true)
        q    = if dih then (0 until 20).map(c => cornerOrbits(20, m, Some(c))).min else cornerOrbits(20, m, None)
        if q <= 4
      yield (m, dih, q)
    survivors shouldBe List((4, true, 3))
    // D4 forces point group D4, so P = 8 (no 3-fold is available: 3 divides none of 4, 5, 20)
    // forced faces: the 20-gon (1/cell, 20 corners); pentagons, stabiliser at most a reflection since 5 is
    // coprime to every crystallographic order, so >= 4 per cell and 20 corners; a square, >= 1 per cell
    val (vLo, vHi, c) = chain(8, 20, 8, 3, 4, 20 + 4 * 5 + 4, 1 + 4 + 1)
    vLo shouldBe 20
    vHi shouldBe 28
    c shouldBe 29
    c should be < 12 * 4 // improves on the G0 bound of 48
    // the bound bites only in its worst case: V is 8/|Stab| summed over four orbits, and only a fourth
    // orbit with TRIVIAL stabiliser reaches C > 24 — every other V lands inside the searched window
    val perV = List(20, 22, 24, 28).map(v => v -> (3 * v - (20 + 4 * 5 + 4 - 3 * 6)) / 2)
    perV shouldBe List(20 -> 17, 22 -> 20, 24 -> 23, 28 -> 29)
    perV.filter(_._2 > 24).map(_._1) shouldBe List(28)

  // ---- witness consistency: the corner-orbit lemma against every banked tiling --------------------------

  private def symbolFromKey(key: String): DSymbol =
    val rows          = key.split(";").map(_.trim).filter(_.nonEmpty)
    val n             = rows.length
    val op            = Array.ofDim[Int](n + 1, 3)
    val m01           = Array.ofDim[Int](n + 1)
    val m12           = Array.ofDim[Int](n + 1)
    for (r, i) <- rows.zipWithIndex do
      val Array(ops, ms) = r.split('|')
      val parts          = ops.split(',').map(_.toInt)
      op(i + 1)(0) = parts(0); op(i + 1)(1) = parts(1); op(i + 1)(2) = parts(2)
      m01(i + 1) = parts(3); m12(i + 1) = ms.toInt
    val dset          = new DSet(op)
    val (orbs, index) = DelaneySymbols.collectOrbits(dset)
    val vs            = Array.tabulate(orbs.length): k =>
      val o = orbs(k)
      val d = o.elements.head
      (if o.i == 0 then m01(d) else m12(d)) / o.r
    new DSymbol(dset, orbs, index, vs)

  /** Every corner-orbit count a crystallographic stabiliser of a regular `n`-gon can produce. */
  private def achievableOrbitCounts(n: Int): Set[Int] =
    (for
      m   <- admissibleRotations(n)
      cnt <- cornerOrbits(n, m, None) +: (0 until n).map(c => cornerOrbits(n, m, Some(c)))
    yield cnt).toSet

  it should "not contradict any banked witness (falsification against real tilings)" in:
    // the stabiliser floor says the corners of a regular n-gon whose letter occurs ONCE in z meet at least
    // ceil(n / 2m) vertex orbits. Every banked witness IS a tiling, so a witness whose anchor tile
    // meets FEWER orbits than any crystallographic stabiliser permits would refute the lemma.
    var checked = 0
    for (name, z, k) <- SaturationProbe.entries do
      val ds       = symbolFromKey(k)
      val vertexOs = ds.orbs.zipWithIndex.collect { case (o, idx) if o.i == 1 => idx -> o.elements.toSet }
      val n        = z.max
      if z.count(_ == n) == 1 then
        // the face orbits that ARE regular n-gons: degree n
        for (o, fi) <- ds.orbs.zipWithIndex if o.i == 0 && ds.m(0, 1, o.elements.head) == n do
          val chambers = o.elements.toSet
          val met      = vertexOs.count((_, elems) => (elems & chambers).nonEmpty)
          val allowed  = achievableOrbitCounts(n)
          val floor    = allowed.min
          val uniform  = vertexOs.size
          println(f"$name%-34s anchor $n%2d-gon (orbit $fi%2d): meets $met%2d vertex orbits of $uniform%2d" +
            f"  | lemma floor $floor%2d, achievable ${allowed.toList.sorted.mkString(",")}" +
            (if allowed(met) then "" else "   <-- NOT an achievable stabiliser count"))
          checked += 1
          withClue(s"$name: anchor $n-gon meets $met vertex orbits, below the stabiliser floor $floor: ")(
            met should be >= floor
          )
          withClue(s"$name: anchor meets more orbits than the tiling has: ")(met should be <= uniform)
    checked should be > 5 // the audit must actually have examined witnesses

  // ---- the cap-profile theorem, and the chain at five and six orbits -----------------------------------

  it should "force j+1 vertex orbits to be >= 6-cycles above C = 6(k+j) (cap profile)" in:
    // With at most j orbits at the top cap 24, the largest attainable budget is 24j + 12(k-j), the best
    // remaining cap being 12. Feasibility needs sum12 >= 2C, so 2C > 12(j+k) forces a (j+1)-th orbit to
    // the top cap — attained only by a cycle of length >= 6.
    def maxSumWith(k: Int, j: Int): Int = 24 * j + 12 * (k - j)
    def threshold(k: Int, j: Int): Int  = 6 * (k + j)
    for k <- 2 to 8; j <- 0 until k do
      (2 * threshold(k, j)) shouldBe maxSumWith(k, j)
    // at three orbits the thresholds reproduce the campaign's own window boundaries
    (0 until 3).map(threshold(3, _)) shouldBe Vector(18, 24, 30)
    // and the last one is exactly the odd-slice case, where ALL orbits are cycles and C is therefore even
    threshold(3, 2) shouldBe 12 * 3 - 6
    threshold(4, 3) shouldBe 12 * 4 - 6

  it should "pin the orbit profile of the k = 3 mid-window slices" in:
    // above C = 24 at least two orbits sit at cap 24, so the third satisfies 48 + c3 >= 2C
    def thirdCapAtLeast(c: Int): Int       = 2 * c - 48
    val caps                               = List(4, 6, 8, 12, 24)
    def admissibleThird(c: Int): List[Int] = caps.filter(_ >= thirdCapAtLeast(c)).filter(_ <= 24)
    admissibleThird(25) shouldBe caps
    admissibleThird(27) shouldBe List(6, 8, 12, 24)
    admissibleThird(29) shouldBe List(12, 24)
    admissibleThird(30) shouldBe List(12, 24)
    // at C = 29 a third orbit at cap 24 would make three cycles and force C even (odd slice), so its cap is
    // exactly 12 — a chain of length >= 3 or a 4-cycle — and C odd rules the 4-cycle out: an ODD chain.
    // The measured slice is correspondingly thin: 10 D-sets against 2,014 at C = 28.
    admissibleThird(29).filter(_ < 24) shouldBe List(12)

  it should "bound (3.7.42) at 33 chambers for k <= 5, leaving only 30-33" in:
    // at k <= 5 the 42-gon's only surviving stabiliser is still D6: C6 and D3 leave 7 corner orbits
    val survivors =
      for
        m   <- admissibleRotations(42)
        dih <- List(false, true)
        q    = if dih then (0 until 42).map(c => cornerOrbits(42, m, Some(c))).min else cornerOrbits(42, m, None)
        if q <= 5
      yield (m, dih, q)
    survivors shouldBe List((6, true, 4))
    // forced faces per cell: the 42-gon (1), heptagons (>= 12/2 = 6, since 7 is coprime to every
    // crystallographic rotation order), triangles (>= 12/6 = 2)
    val (_, _, c) = chain(12, 42, 12, 4, 5, 42 + 6 * 7 + 2 * 3, 1 + 6 + 2)
    c shouldBe 33
    c should be < 12 * 5 // the G0 bound would permit 60
    // <= 24 and 25-29 are already exhausted, so the row's k >= 6 needs four chamber counts
    (30 to c).toList shouldBe List(30, 31, 32, 33)

  it should "bound (3.7.42) at 45 chambers for k <= 6" in:
    val (_, _, c) = chain(12, 42, 12, 4, 6, 42 + 6 * 7 + 2 * 3, 1 + 6 + 2)
    c shouldBe 45
    c should be < 12 * 6

  it should "bound (4.5.20) at 41 chambers for k <= 5" in:
    // three stabiliser types survive k <= 5 on the 20-gon; the WEAKEST bound governs
    val survivors =
      for
        m   <- admissibleRotations(20)
        dih <- List(false, true)
        q    = if dih then (0 until 20).map(c => cornerOrbits(20, m, Some(c))).min else cornerOrbits(20, m, None)
        if q <= 5
      yield (m, dih, q)
    survivors.map(_._3).sorted shouldBe List(3, 5, 5)
    // D4 on the 20-gon, point group D4 so P = 8: pentagons >= 8/2 = 4 per cell, one square
    val d4        = chain(8, 20, 8, 3, 5, 20 + 4 * 5 + 4, 1 + 4 + 1)._3
    // C4 or D2 (order 4) with P = 8: two 20-gons per cell, five corner orbits and no slack left
    val c4        = chain(8, 20, 4, 5, 5, 2 * 20 + 4 * 5 + 4, 2 + 4 + 1)._3
    d4 shouldBe 41
    c4 should be <= d4
    math.max(d4, c4) should be < 12 * 5

  // ---- the two-anchor structure of (3.7.42) at five orbits ---------------------------------------------

  /** The multiset of corner-orbit SIZES of a regular n-gon under the given stabiliser. */
  private def cornerOrbitSizes(n: Int, m: Int, reflection: Option[Int]): List[Int] =
    val step  = n / m
    val group = (0 until m).map(s => (i: Int) => Math.floorMod(i + s * step, n)) ++
      reflection.toList.flatMap(c => (0 until m).map(s => (i: Int) => Math.floorMod(c - i + s * step, n)))
    val seen  = scala.collection.mutable.Set.empty[Int]
    val out   = scala.collection.mutable.ListBuffer.empty[Int]
    for p <- 0 until n if !seen(p) do
      var orbit = Set(p); var grown = true
      while grown do
        val next = orbit.flatMap(q => group.map(_(q))); grown = next != orbit; orbit = next
      seen ++= orbit; out += orbit.size
    out.toList.sorted

  it should "force the heptagon of (3.7.42) to a reflection stabiliser at k <= 5" in:
    // 7 is coprime to every crystallographic rotation order, so Stab is trivial or one reflection
    admissibleRotations(7) shouldBe List(1)
    cornerOrbits(7, 1, None) shouldBe 7 // trivial: 7 corner orbits, above k = 5
    (0 until 7).map(c => cornerOrbits(7, 1, Some(c))).distinct shouldBe Vector(4)
    // hence at k <= 5 the reflection is FORCED, and with it 12/2 = 6 heptagons per primitive cell
    val heptagonsPerCell = 12 / 2
    heptagonsPerCell shouldBe 6
    (heptagonsPerCell * 7) shouldBe 42 // heptagon-corner vertices per cell

  it should "give both anchors of (3.7.42) the same per-cell orbit profile" in:
    // the 42-gon at k <= 5 is D6 (order 12), one copy per cell
    cornerOrbitSizes(42, 6, Some(0)) shouldBe List(6, 12, 12, 12)
    // per-cell vertex count of an orbit is 12 / |Stab of a corner|, and a corner of the single
    // 42-gon has stabiliser 12 / (its orbit size within the tile)
    cornerOrbitSizes(42, 6, Some(0)).map(sz => 12 / (12 / sz)) shouldBe List(6, 12, 12, 12)
    // the heptagon at k <= 5 is D1 (order 2), six copies per cell
    cornerOrbitSizes(7, 1, Some(0)) shouldBe List(1, 2, 2, 2)
    // a corner in an orbit of size t within the tile has stabiliser 2 / t, so 12 / (2/t) = 6t per cell
    cornerOrbitSizes(7, 1, Some(0)).map(t => 6 * t) shouldBe List(6, 12, 12, 12)
    // BOTH anchors therefore contribute 6 + 12 + 12 + 12 = 42 vertices per cell, in four orbits
    cornerOrbitSizes(42, 6, Some(0)).sum shouldBe 42
    cornerOrbitSizes(7, 1, Some(0)).map(6 * _).sum shouldBe 42

  it should "force the two anchor orbit families to share at least three of the five" in:
    val k                         = 5; val q42 = 4; val q7 = 4
    // |A| + |B| - |A union B| <= |A cap B|, and the union is bounded by the uniformity
    (q42 + q7 - k) shouldBe 3
    // Euler closes the chain as C <= V - 21, with V = 42 + b and b = 12/s5 the fifth orbit's
    // per-cell count; the bound is therefore governed entirely by that single orbit
    def chamberFromV(v: Int): Int = v - 21
    chamberFromV(42) shouldBe 21      // k = 4: no fifth orbit, and the row is already closed there
    chamberFromV(42 + 6) shouldBe 27  // a fifth orbit on a mirror
    chamberFromV(42 + 12) shouldBe 33 // a fifth orbit with TRIVIAL stabiliser: the open case
    // so sharpening C <= 33 means excluding exactly one configuration
    List(1, 2, 3, 4, 6, 12).map(s => 12 / s).map(b => chamberFromV(42 + b)).max shouldBe 33

  it should "close (3.7.42) at k <= 5 by counting irregular tiles" in:
    // Every face of a (3.7.42) tiling is a 42-gon, a heptagon, a triangle, or irregular. A unit-edge
    // 3-gon is EQUILATERAL hence regular, so an irregular tile has at least FOUR corners - the step the
    // generic chain missed by allowing 3.
    val v                                 = 54 // the surviving case: fifth orbit with trivial stabiliser
    // at most one heptagon orbit and one 42-gon orbit: a second would add >= 6 heptagons (Stab <= 2)
    // or >= 1 further 42-gon, and their corners are distinct vertices
    (2 * 6 * 7) should be > v
    (2 * 42) should be > v
    // faces: 1 forty-two-gon (42 corners), 6 heptagons (42), t triangles (3t), i irregular (S >= 4i)
    // Euler with 2E = sum n_f and E = V + F gives S = 2V - 70 - t + 2i
    def sOf(vv: Int, t: Int, i: Int): Int = 2 * vv - 70 - t + 2 * i
    sOf(54, 0, 0) shouldBe 38
    // S >= 4i bounds i, and no vertex carries two triangles so 3t <= V
    def maxChambers(vv: Int): Int         =
      (for
        t <- 0 to vv / 3
        i <- 0 to vv
        if sOf(vv, t, i) >= 4 * i && sOf(vv, t, i) >= 0
      yield 4 * (vv + 7 + t + i) / 12).max
    maxChambers(54) shouldBe 29
    // and the bound is monotone below, so every admissible V lands at or under it
    (43 to 54).map(maxChambers).max shouldBe 29
    // 29 is INSIDE the exhausted windows, which hold zero (3.7.42) candidates in either regime
    maxChambers(54) should be <= 29
    maxChambers(54) should be < 12 * 5

  // ---- the same audit for (4.5.20) ---------------------------------------------------------------------

  it should "admit no 3-corner tile at all in (4.5.20)" in:
    // 3 is not a letter of z, so a regular triangle cannot occur; and a unit-edge 3-gon is equilateral,
    // hence regular, so it cannot occur as an irregular tile either. NO face has three corners, and the
    // residual faces obey S >= 4i exactly as in (3.7.42) - a non-square rhombus supplies the 4.
    List(4, 5, 20) should not contain 3

  it should "force the pentagon of (4.5.20) to a reflection stabiliser at k <= 4" in:
    admissibleRotations(5) shouldBe List(1)
    cornerOrbits(5, 1, None) shouldBe 5 // trivial: 5 orbits, above k = 4
    (0 until 5).map(c => cornerOrbits(5, 1, Some(c))).distinct shouldBe Vector(3)
    // so 8/2 = 4 pentagons per cell, 20 corners, three orbits - the 20-gon's D4 profile exactly
    cornerOrbitSizes(20, 4, Some(0)).map(sz => 8 / (8 / sz)) shouldBe List(4, 8, 8)
    cornerOrbitSizes(5, 1, Some(0)).map(t => 4 * t) shouldBe List(4, 8, 8)

  /** Chambers for (4.5.20) with point group order 8: one 20-gon orbit (20 corners), one pentagon orbit (20
    * corners), q squares and i irregular tiles per cell, no 3-corner faces so S >= 4i.
    */
  private def chambers4520(v: Int, twentyCorners: Int, pentaCorners: Int, knownFaces: Int): Int =
    (for
      q <- 0 to v / 4                                     // no vertex carries two squares, so 4q <= V
      i <- 0 to v
      f  = knownFaces + q + i
      e  = v + f                                          // Euler on the torus quotient: V - E + F = 0
      ss = 2 * e - (twentyCorners + pentaCorners) - 4 * q // corners left over for the irregular tiles
      if ss >= 4 * i && ss >= 0 // and no face of this species has three corners
    yield 4 * e / 8).max

  it should "sharpen (4.5.20) to 23 chambers at k <= 4, inside the exhausted window" in:
    // V <= 28 from the chain; one 20-gon (20 corners) and four pentagons (20 corners), 5 known faces
    chambers4520(28, 20, 20, 5) shouldBe 23
    (20 to 28).map(chambers4520(_, 20, 20, 5)).max shouldBe 23
    // every (4.5.20) candidate the <= 24 sweep actually found sits at or below 23 - the bound predicts
    // the data: the ten candidates are at 16, 18, 18, 18, 18, 20, 20, 20, 22, 22 chambers
    List(16, 18, 18, 18, 18, 20, 20, 20, 22, 22).max should be <= 23

  it should "sharpen (4.5.20) to 31 chambers at k <= 5, leaving only 30 and 31" in:
    // case A, pentagon with a reflection: the two families of three orbits share at least one, so
    // V = 40 - (shared) <= 36
    val caseA = chambers4520(36, 20, 20, 5)
    // case B, pentagon with trivial stabiliser: 8 pentagons and 40 corners force V = 40 with every
    // orbit trivial, so the 20-gon is C4 with two copies and 40 corners, over 10 known faces
    val caseB = chambers4520(40, 40, 40, 10)
    caseA shouldBe 31
    caseB shouldBe 30
    math.max(caseA, caseB) shouldBe 31
    // the <= 24 and 25-29 windows are exhausted, so k >= 6 needs exactly two chamber counts
    (30 to 31).toList shouldBe List(30, 31)

  /** The corner indices of each orbit of a regular n-gon under <rotation by n/m> plus reflection i -> c-i. */
  private def cornerOrbitSets(n: Int, m: Int, c: Int): List[Set[Int]] =
    val step  = n / m
    val group = (0 until m).map(t => (i: Int) => Math.floorMod(i + t * step, n)) ++
      (0 until m).map(t => (i: Int) => Math.floorMod(c - i + t * step, n))
    val seen  = scala.collection.mutable.Set.empty[Int]
    val out   = scala.collection.mutable.ListBuffer.empty[Set[Int]]
    for p <- 0 until n if !seen(p) do
      var orbit = Set(p); var grown = true
      while grown do
        val next = orbit.flatMap(q => group.map(_(q))); grown = next != orbit; orbit = next
      seen ++= orbit; out += orbit
    out.toList

  it should "refute V = 36 for (4.5.20) when the anchors share exactly one orbit" in:
    // V = 36 with a single shared orbit forces that orbit to be the per-cell-count-4 one, the
    // reflection-fixed corners of the 20-gon under D4.
    val orbits   = cornerOrbitSets(20, 4, 0)
    orbits.map(_.size).sorted shouldBe List(4, 8, 8)
    val small    = orbits.find(_.size == 4).get
    // its corners sit 5 apart on the 20-gon, so NO two of them are adjacent
    val adjacent = small.exists(i => small(Math.floorMod(i + 1, 20)) || small(Math.floorMod(i - 1, 20)))
    adjacent shouldBe false
    // The z-vertex needs a square, a pentagon AND a 20-gon, so it lies in a shared orbit - here the
    // only one. Its angles 90 + 108 + 162 = 360 make it valence 3, and in the cyclic order (4.5.20)
    // the pentagon and the 20-gon are neighbours, so they share an EDGE of the 20-gon. Both endpoints
    // of that edge carry both tiles, hence both lie in the shared orbit - two ADJACENT corners of the
    // 20-gon inside an orbit that contains no adjacent pair. Contradiction.
    (90 + 108 + 162) shouldBe 360
    // so the single-shared-orbit route to V = 36 is impossible, and sharing one count-8 orbit gives 32
    (40 - 8) shouldBe 32

  it should "leave only the coincident-families route to V = 36 for (4.5.20)" in:
    // the two families have the same profile 4, 8, 8; V = 40 - (shared sum) when the union is five
    val profile   = List(4, 8, 8)
    val bySharing =
      profile.toSet.subsets().filter(_.nonEmpty).map(sub => sub.sum -> (40 - sub.sum)).toMap
    bySharing.get(4) shouldBe Some(36) // refuted above: the shared orbit has no adjacent pair
    bySharing.get(8) shouldBe Some(32)
    bySharing.get(12) shouldBe Some(28)
    (profile.sum + 8 + 8) shouldBe 36
    // there the extra orbits lie on neither anchor, so their RVS is a bare square with 270 degrees
    // of irregular corner, and they force at least 16 square-corner incidences
    (20 - 5) shouldBe 15 // residue in pi/10 units at such a vertex
    (2 * 8) shouldBe 16

  it should "constrain, but not yet refute, the coincident-families configuration of (4.5.20)" in:
    // Setting the count-4 orbit at position 0, D4 = <rotation by 5, i -> -i> labels the 20-gon's
    // corners around its boundary with period 5.
    val label = (0 until 20).map { i =>
      val o = cornerOrbitSets(20, 4, 0)
      if o.find(_.size == 4).get(i) then "A" else if o.filter(_.size == 8).head(i) then "B" else "C"
    }
    label.take(5).mkString shouldBe label.slice(5, 10).mkString // period 5
    label.count(_ == "A") shouldBe 4

    // Every corner of the 20-gon carries exactly one pentagon (no vertex has two), so with e
    // pentagons sharing an EDGE and v touching at a single vertex, 2e + v = 20. A pentagon's own
    // stabiliser has order 2, so under Stab(20-gon) = D4 the touching pentagons come in orbits of
    // size 4 or 8, making T = e + v a multiple of 4; and e = 20 - T.
    val touching = (4 to 20 by 4).filter(t => (20 - t) >= 0 && (20 - t) <= t)
    // e = 0 is excluded: the all-regular vertex is valence 3 with the pentagon and 20-gon adjacent
    touching.filter(t => 20 - t > 0) shouldBe Vector(12, 16)

    // squares: the two extra orbits carry one each (16 incidences) and the shared orbits only at
    // their all-regular vertices, x of them, x a nonempty sub-sum of the profile
    val xs = List(4, 8, 12, 16, 20)
    xs.map(x => (16 + x) / 4) shouldBe List(5, 6, 7, 8, 9) // squares per cell
    xs.forall(x => (16 + x) % 4 == 0) shouldBe true

    // Euler at V = 36 gives C = (41 + q + i)/2 with i <= 21 - q, so C >= 30 needs q + i >= 19; at the
    // extreme S = 4i exactly and EVERY irregular tile is a quadrilateral - a unit-edge one is a
    // rhombus. The vertex arithmetic then forces its angles: 90 + 135 + 135 at the bare-square
    // vertices and 162 + 108 + 45 + 45 at the others, i.e. a single 45/135 rhombus type.
    (90 + 135 + 135) shouldBe 360
    (162 + 108 + 45 + 45) shouldBe 360
    val q  = 5; val i = 16
    val sS = 42 - 2 * q + 2 * i
    sS shouldBe 4 * i // every irregular face is a quadrilateral at this extreme
    ((41 + q + i) / 2) shouldBe 31
    // 45 degrees is not a multiple of the 20-gon's 18-degree edge grid - the suspected obstruction,
    // NOT yet a proof, since irregular angles need only sum to a multiple of 18 at each vertex
    (45 % 18) should not be 0
    (90 % 18, 108 % 18, 162 % 18) shouldBe (0, 0, 0)

  it should "record that the edge-direction grid does NOT refute the 45-degree rhombus" in:
    // The suspected obstruction was that 45 degrees is off the 18-degree grid the 20-gon imposes.
    // Accumulating the interior angles around the shared vertex 20-gon(162), pentagon(108),
    // rhombus(45), rhombus(45) shows the fourth edge IS off that grid:
    val dirs                     = List(162, 108, 45, 45).scanLeft(0)(_ + _).init
    dirs shouldBe List(0, 162, 270, 315)
    dirs.map(_ % 18 == 0) shouldBe List(true, true, true, false)
    dirs.sum + 45 - dirs.sum shouldBe 45 // the star closes: 162 + 108 + 45 + 45 = 360
    List(162, 108, 45, 45).sum shouldBe 360
    // but that is NOT a contradiction. The angles present generate a FINER lattice, not an
    // inconsistent one: gcd(162, 108, 90, 45, 135) = 9, so directions live on a 9-degree grid,
    // and the cyclotomic field agrees - the denominators of the angles over pi are 10, 5, 2, 4,
    // with lcm 20, so N = 40 and edge vectors are 40th roots of unity, i.e. 9-degree steps.
    def gcd(a: Int, b: Int): Int = if b == 0 then a else gcd(b, a % b)
    List(162, 108, 90, 45, 135).reduce(gcd) shouldBe 9
    gcd(162, 360) shouldBe 18 // the 20-gon alone would give 18
    (360 / 9) shouldBe 40     // the refined lattice is 40-fold
    // so the rhombus merely refines Q(zeta_20) to Q(zeta_40) and the configuration survives this
    // line of attack entirely. Do not retry it.

  it should "show the surviving (4.5.20) configuration is AUTOMATICALLY saturated" in:
    // A split-off piece must be a regular polygon whose letter lies in z, else its corners violate
    // condition (3). The irregular tiles here are 45/135 unit rhombi, of area sin(45 deg); every
    // candidate is strictly larger, so none fits inside and NO split exists.
    def regArea(n: Int): Double = n / (4.0 * math.tan(math.Pi / n))
    val rhombus                 = math.sin(math.toRadians(45))
    List(4, 5, 20).forall(n => regArea(n) > rhombus) shouldBe true
    regArea(4) should be > rhombus // the smallest candidate already exceeds it
    // saturation therefore cannot refute the configuration - it holds automatically. If the object
    // exists it is a SATURATED uniformity-5 tiling of (4.5.20), settling that row at exactly 5 and
    // refuting the conjectured 7. Its combinatorics are fully determined:
    val twentyGons = 1; val pentagons = 4; val squares = 5; val rhombi = 16
    val f          = twentyGons + pentagons + squares + rhombi
    val v          = 36
    val e          = v + f // Euler on the torus quotient
    f shouldBe 26
    e shouldBe 62
    (20 * twentyGons + 5 * pentagons + 4 * squares + 4 * rhombi) shouldBe 2 * e // sum of face sizes
    (4 * e / 8) shouldBe 31 // chambers, point group D4

  it should "determine the 20-gon collar of the candidate (4.5.20) witness" in:
    // Every corner of the 20-gon carries exactly one pentagon, so with e pentagons sharing an EDGE
    // and v touching at one vertex, 2e + v = 20 and the number touching is T = e + v = 20 - e.
    // T is a multiple of 4 (D4-orbits of size 4 or 8), so e is too; e <= 10 and e > 0 because the
    // all-regular vertex makes the pentagon and 20-gon adjacent.
    val admissibleE = (0 to 10).filter(e => (20 - e) % 4 == 0 && e > 0)
    admissibleE shouldBe Vector(4, 8)

    // Take e = 8. The corner labels run A B C C B with period 5 (A the count-4 orbit), and the 8
    // pentagon-edges must cover all 16 B/C corners exactly once while avoiding A. Per period the
    // only perfect matching on {1,2,3,4} using edges (1,2),(2,3),(3,4) is {(1,2),(3,4)}.
    val within    = List((1, 2), (2, 3), (3, 4))
    val matchings = within.toSet.subsets().filter { m =>
      val ends = m.toList.flatMap(pr => List(pr._1, pr._2))
      ends.size == 4 && ends.distinct.size == 4 // a genuine perfect matching, no corner reused
    }.toList
    matchings.map(_.toList.sorted) shouldBe List(List((1, 2), (3, 4)))

    // That forces the local types: corner 0 (label A) has both edges non-pentagon, so it is flanked
    // by two rhombi; corners 1 and 4 (label B) carry one pentagon-edge and one rhombus-edge; corners
    // 2 and 3 (label C) share the edge (2,3), and if either is all-regular that edge bears a square,
    // making both all-regular. An edge has ONE tile on its far side, so corner 1 cannot be
    // all-regular - its non-pentagon edge (0,1) already meets the A corner's rhombus.
    // The consistent assignment is therefore: A flanked by rhombi, B mixed, C all-regular.
    val allRegularOnTwentyGon = 8            // orbit C
    val x                     = 8            // all-regular vertices per cell
    val q                     = (16 + x) / 4 // squares per cell
    q shouldBe 6
    // C = (41 + q + i)/2 with 19 - q <= i <= 21 - q leaves exactly two chamber counts
    val cs                    = ((19 - q) to (21 - q)).filter(i => (41 + q + i) % 2 == 0).map(i => (41 + q + i) / 2)
    cs shouldBe Vector(30, 31)
    // NO contradiction emerges: the collar closes consistently, which is evidence FOR the object

  it should "kill e = 4 and one of the e = 8 collars for the (4.5.20) candidate" in:
    // Edge k of the 20-gon joins corners k and k+1; D4 acts by k -> k+5 and k -> -k-1.
    def edgeOrbit(k: Int): Set[Int] =
      var o = Set(k); var grown = true
      while grown do
        val n = o.flatMap(e => Set(Math.floorMod(e + 5, 20), Math.floorMod(-e - 1, 20))) ++ o
        grown = n != o; o = n
      o
    val orbits                      = (0 until 20).map(edgeOrbit).distinct.sortBy(_.size)
    orbits.map(_.size) shouldBe Seq(4, 8, 8)
    orbits.head shouldBe Set(2, 7, 12, 17)

    // e = 8, using the orbit {0,4,5,...}: corner 0's two edges are 19 and 0, BOTH pentagon-edges,
    // so that corner would carry two pentagons - impossible, 5 occurring once in z.
    val bad8 = orbits.find(o => o.size == 8 && o.contains(0)).get
    (bad8(19) && bad8(0)) shouldBe true

    // e = 4 dies without any assumption about tile shapes. The all-regular vertex has the 20-gon
    // adjacent to a pentagon, so it is an endpoint of a pentagon-edge, i.e. corner 2 or 3 (orbit C).
    // Say corner 2: its edges are (1,2) and (2,3); (2,3) bears the pentagon, so (1,2) bears the
    // square. Corner 1 then has 162 + 90 + 108 = 360 exactly - the 20-gon, that square, and the
    // pentagon every corner carries - so it is valence 3 and the pentagon must be adjacent across
    // its other edge (0,1). But 0 is not in the pentagon-edge orbit {2,7,12,17}.
    (162 + 90 + 108) shouldBe 360
    orbits.head.contains(0) shouldBe false

    // e = 8 with the orbit {1,3,6,...} survives at C = 30 but NOT at C = 31. At C = 31 every
    // irregular tile is a 45/135 rhombus, whose angles alternate, so every edge joins a 45 corner
    // to a 135 corner. Corner 0 (label A) has both edges non-pentagon and reads
    // 162 + 45 + 108 + 45, and corner 1 reads 162 + 108 + 45 + 45 - so the rhombus on the shared
    // edge (0,1) would show 45 at BOTH of its endpoints. Impossible.
    (162 + 45 + 108 + 45) shouldBe 360
    (162 + 108 + 45 + 45) shouldBe 360
    // at C = 30 the irregular tiles are not all quadrilaterals, so the parity argument lapses
    val v   = 36; val q = 6
    val sAt = (i: Int) => 2 * v - 30 - 2 * q + 2 * i
    sAt(15) shouldBe 4 * 15 // C = 31: every irregular face is a quadrilateral
    sAt(13) should be > 4 * 13 // C = 30: some face has five or more corners

  it should "refute V = 36 outright, closing (4.5.20) at k >= 6" in:
    // In the surviving case i = 13 irregular tiles carry S = 56 corners, none with fewer than four,
    // so the excess sum(n - 4) is 4. It is distributed over G-ORBITS: an orbit of size m = 8/s
    // contributes m(n - 4), and a tile of stabiliser order s must admit a symmetry of that order.
    def admissible(s: Int, n: Int): Boolean = n >= 4 && (s match
      case 8 => n % 4 == 0 && n != 4 // D4; n = 4 would be a square, which is regular
      case 4 => n % 2 == 0           // C4 needs 4 | n, D2 needs n even; n = 4 is the rhombus
      case 2 => true // C2 or a single reflection
      case _ => true)
    val carriers                            =
      for
        s <- List(8, 4, 2, 1); m = 8 / s; n <- 4 to 12
        if admissible(s, n) && m * (n - 4) == 4
      yield (m, n)
    carriers shouldBe List((1, 8), (2, 6), (4, 5))

    // A non-square rhombus has shape symmetry D2, so |Stab| <= 4 and its orbit size 8/|Stab| is
    // EVEN. The rhombi number 13 - m, which must therefore be even.
    carriers.filter((m, _) => (13 - m) % 2 == 0) shouldBe List((1, 8))

    // The survivor is one D4-symmetric irregular octagon per cell. Its eight corners are a union of
    // whole vertex orbits, and the five orbits have per-cell counts 4, 8, 8, 8, 8 - only ONE has
    // count 4, so the octagon's corners cannot be two orbits of four and must be a single orbit of
    // eight. Then all eight corners are G-equivalent, so the octagon is equiangular; with unit edges
    // that makes it REGULAR, and 8 is not a letter of z, so its corners violate condition (3).
    val orbitCounts = List(4, 8, 8, 8, 8)
    orbitCounts.sum shouldBe 36
    orbitCounts.count(_ == 4) shouldBe 1 // cannot supply two orbits of four
    orbitCounts.filter(_ == 8).nonEmpty shouldBe true
    List(4, 5, 20) should not contain 8  // a regular octagon is inadmissible in this species

    // Every route to V = 36 is therefore closed, so V <= 32 and C <= V - 5 = 27 - inside the
    // <= 24 and 25-29 windows, both exhausted in both valence regimes with no surviving candidate.
    val v = 32
    chambers4520(v, 20, 20, 5) should be <= 27
    (20 to 32).map(chambers4520(_, 20, 20, 5)).max shouldBe 27

  // ---- stronger tests of the chain: 2,240 banked symbols, and species where a k-tiling EXISTS ------------

  it should "hold the stabiliser floor over every banked candidate symbol, not merely the witnesses" in:
    // The witness audit covered ~24 patterns. The four-orbit sweeps banked 2,240 candidate symbols
    // with their canonical keys; the stabiliser floor must hold on every one. For each, rebuild the symbol,
    // take the largest letter of z occurring ONCE, and confront the vertex orbits its face orbit
    // meets with the counts a crystallographic stabiliser can produce.
    val dir     = java.nio.file.Path.of("certs", "uclass-k4")
    val files   = if java.nio.file.Files.isDirectory(dir) then
      java.nio.file.Files.list(dir).toArray.map(_.asInstanceOf[java.nio.file.Path])
        .filter(_.getFileName.toString.startsWith("window-hits")).toList
    else Nil
    assume(files.nonEmpty, "banked hits files absent - regenerate certs/uclass-k4")
    var checked = 0
    var species = Set.empty[String]
    for f <- files; line <- java.nio.file.Files.readAllLines(f).asScala.drop(1) do
      val cols = line.split('\t').map(_.trim)
      val zStr = cols.find(_.startsWith("z=")).get.stripPrefix("z=")
      val key  = cols.find(_.startsWith("key=")).get.stripPrefix("key=")
      val z    = zStr.split('.').map(_.toInt).toList
      val n    = z.max
      if z.count(_ == n) == 1 then
        val ds       = symbolFromKey(key)
        val vertexOs = ds.orbs.zipWithIndex.collect { case (o, i) if o.i == 1 => o.elements.toSet }
        for o <- ds.orbs if o.i == 0 && ds.m(0, 1, o.elements.head) == n do
          val chambers = o.elements.toSet
          val met      = vertexOs.count(e => (e & chambers).nonEmpty)
          withClue(s"z=$zStr key=${key.take(24)}: anchor $n-gon meets $met orbits, "):
            achievableOrbitCounts(n) should contain(met)
            met should be <= vertexOs.size
          checked += 1
          species += zStr
    println(
      s"stabiliser floor checked on $checked anchor incidences across ${species.size} species, ${files.size} files"
    )
    checked should be > 500

  it should "not under-predict chambers for species where a k = 4 tiling is KNOWN to exist" in:
    // The chain gives an UPPER bound on C. Three species have a four-orbit tiling with a known
    // chamber count, so a bound below it would refute the chain outright. Parameters are taken at
    // their weakest admissible setting, anchor tile only, which is the safest form of the bound.
    def weakBound(pointGroup: Int, n: Int, anchorStab: Int, q: Int, k: Int): Int =
      val vLo   = n * (pointGroup / anchorStab)
      val vHi   = vLo + (k - q) * pointGroup
      val faces = pointGroup / anchorStab
      val f     = 2 * vHi - (n * faces - 3 * faces)
      4 * (vHi + f) / pointGroup
    // (3.9.18): 18-gon, observed q = 3, stabiliser of order 6 in a point group of order 6 or 12
    weakBound(6, 18, 6, 3, 4) should be >= 24
    weakBound(12, 18, 12, 2, 4) should be >= 24
    // (5^2.10): the 10-gon is the letter occurring once; observed q = 3 under D2
    weakBound(4, 10, 4, 3, 4) should be >= 18
    weakBound(8, 10, 4, 3, 4) should be >= 18
    // (3.4^2.6): 6-gon, observed q = 3, saturated patterns at 30 chambers
    weakBound(4, 6, 2, 3, 4) should be >= 30
    weakBound(12, 6, 2, 3, 4) should be >= 30

  it should "pin step (ii): only D6 carries both a 3-fold and a 2-fold rotation with reflections" in:
    // the ten crystallographic point groups, as (rotation order, has a reflection)
    val pointGroups = List(
      ("C1", 1, false),
      ("C2", 2, false),
      ("C3", 3, false),
      ("C4", 4, false),
      ("C6", 6, false),
      ("D1", 1, true),
      ("D2", 2, true),
      ("D3", 3, true),
      ("D4", 4, true),
      ("D6", 6, true)
    )
    pointGroups.size shouldBe 10
    // a group containing a 3-fold AND a 2-fold rotation has rotation order divisible by 6
    val withBoth    = pointGroups.filter((_, r, _) => r % 3 == 0 && r % 2 == 0)
    withBoth.map(_._1) shouldBe List("C6", "D6")
    // adding reflections leaves exactly D6, and p6m is the unique wallpaper group with that point group
    withBoth.filter(_._3).map(_._1) shouldBe List("D6")
    // for (4.5.20) no 3-fold is available at all, since 3 divides none of its letters
    List(4, 5, 20).exists(_ % 3 == 0) shouldBe false
    // so its point group has rotation order in {1,2,4} and, with the forced reflections, is D4
    pointGroups.filter((_, r, h) => h && r % 3 != 0).map(_._1) shouldBe List("D1", "D2", "D4")

  it should "pin step (iii): a sub-60-degree corner can never belong to a regular tile" in:
    // the argument needs the SMALLEST regular corner angle to be 60 degrees, which it is - the
    // equilateral triangle - so if a 6-fold vertex splits 60 degrees over t >= 2 classes, every
    // angle is strictly below 60 and no incident tile can be regular, emptying the RVS
    def corner(p: Int): Double = 180.0 * (p - 2) / p
    (3 to 100).map(corner).min shouldBe 60.0
    corner(3) shouldBe 60.0
    // and at t = 1 the six congruent tiles would read (3,3,3,3,3,3), longer than any z in the table
    UClass.targets.map(_._1.length).max should be < 6
    // both branches therefore violate condition (2) or (3), which is the content of step (iii)
    UClass.targets.forall((z, _) => !UClass.cyclicSubset(List.fill(6)(3), z)) shouldBe true
